rsp23: Create API Gateway
NolanCampbell2357/senior-project-2024 pull request #5
Opened 2024-03-05 22:10 UTC by lcmackey

gateway-rsp-test-gateway-swagger.json is the API definition file. It contains a mock integration and no methods because we have no Lambda functions as of yet. Please let me know if there is anything else I should commit to the repo to init Gateway.

2024-03-11 00:50 UTC, NolanCampbell2357 requested changes

2024-03-11 00:50 UTC, NolanCampbell2357 commented on gateway-rsp-test-gateway-swagger.json
> +{
I am unfamiliar with Swagger. Can you give me a brief explanation of what we will use this file for please? If this is Infrastructure as Code (IaC) then can you drop this into the `iac` folder instead.

2024-03-11 23:46 UTC, lcmackey reviewed
Will change Swagger API spec to OpenAPI 3.0 spec.

2024-03-13 04:34 UTC, NolanCampbell2357 approved these changes
Radical

2024-03-13 22:18 UTC, merged